Vbox/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from users import urls as users_url
from selectos import urls as selectos_url
from webssh import urls as ssh_url
from file import urls as file_url
from component import urls as comp_url

from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(users_url)),
    path('selectos/', include(selectos_url)),
    path('file/', include(file_url)),
    path('webssh/', include(ssh_url)),
    path('webguacamole/', include('webguacamole.urls', namespace='webguacamole')),
    path('component/', include(comp_url)),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # url(r'^api-auth/', include('rest_framework.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file/urls.py
from django.urls import path
from django.conf.urls import url
from .views import File_upload

urlpatterns = [
    path('file_upload/', File_upload.as_view(), name='file_upload'),
    # path('file_list/', xxxx, name='file_list')
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from .views import Login, logout, Registered, profile, index, bash_info

app_name = 'users'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout', logout, name='logout'),
    path('registered/', Registered.as_view(), name='registered'),
    path('profile/', profile, name='profile'),
    path('index/', index, name='index'),
    path('bash_info/', bash_info, name='bash_info'),  # 异步加载信息传递方案
]

file/models.py
from django.db import models

# Create your models here.


class Papers(models.Model):
    user = models.ForeignKey('users.UserProfile', to_field='username', related_name='file_upload_user', null=False,
                             on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=100, null=False, verbose_name='文件名')
    size = models.IntegerField(default=1024, verbose_name='文件大小')
    create_time = models.DateTimeField('上传时间', auto_now_add=True)

file/views.py
from django.shortcuts import render
from django.http import JsonResponse
from users.models import UserProfile
from django.views.generic import View
from tools.logs import event_log, save_file_log
from tools.tool import login_required
from Vbox import celery_app
import os
# 对类视图使用装饰器需要使用这个方法
from django.utils.decorators import method_decorator


@celery_app.task
def save_file(username, file_obj, nickname, REMOTE_ADDR, HTTP_USER_AGENT):
    try:
        with open('%s/%s' % ('/home/soul/tools/' + username, file_obj.name),
                  "wb") as f:  # 打开文件
            for chunk in file_obj.chunks():
                f.write(chunk)  # chunk方式写入文件
        event_log.delay(nickname, 1, 23, '[{}] 文件上传成功'.format(nickname), REMOTE_ADDR,
                        HTTP_USER_AGENT, str(file_obj.name))
    except Exception as err:
        event_log.delay(nickname, 1, 23, '[{}] 文件上传失败'.format(nickname), REMOTE_ADDR,
                        HTTP_USER_AGENT, str(err))

@celery_app.task
def delete_file(PATH, FILENAME):
    os.remove(PATH + FILENAME)


@method_decorator(login_required, name='dispatch')
class File_upload(View):

    def get(self, request):
        img = UserProfile.objects.get(username=request.session.get('username', None)).avatar
        nickname = request.session.get('nickname', None)
        role = request.session.get('role', None)
        page = '文件上传'
        event_log.delay(nickname, 1, 22, '[{}] 访问文件上传页面'.format(nickname),
                        request.META.get('REMOTE_ADDR', None), request.META.get('HTTP_USER_AGENT', None),
                        str(request.headers))
        return render(request, 'file/file_upload.html', locals())

    def post(self, request):
        # if request.is_ajax():
        username = request.session.get('username', None)
        nickname = request.session.get('nickname', None)
        REMOTE_ADDR = request.META.get('REMOTE_ADDR', None)
        HTTP_USER_AGENT = request.META.get('HTTP_USER_AGENT', None)
        for k, file_obj in request.FILES.items():  # 获取前端传过来的文件数据
            SIZE = file_obj.size
            FILENAME = file_obj.name
            save_file(username, file_obj, nickname, REMOTE_ADDR, HTTP_USER_AGENT)
            save_file_log(username, FILENAME, SIZE, nickname, REMOTE_ADDR, HTTP_USER_AGENT)
        return JsonResponse({'status': 200, 'error': '上传成功'})

@login_required
def del_file(request):
    PATH = '/home/soul/tools/' + request.session.get('username', None) + '/'
    print('当前路径下文件如下：%s' % os.listdir(PATH))
    for k, file_obj in request.FILES.items():
        FILENAME = file_obj.name
        # 判断文件是否存在
        if os.path.exists(PATH + FILENAME):
            try:
                delete_file(PATH, FILENAME)
                event_log.delay(request.session.get('nickname', None), 1, 25,
                                '[{}] 文件删除成功'.format(request.session.get('nickname', None)),
                                request.META.get('REMOTE_ADDR', None), request.META.get('HTTP_USER_AGENT', None),
                                str(FILENAME))
                return JsonResponse({'status': 200, 'message': '删除成功'})
            except Exception as err:
                event_log.delay(request.session.get('nickname', None), 1, 25,
                                '[{}] 文件删除失败'.format(request.session.get('nickname', None)),
                                request.META.get('REMOTE_ADDR', None), request.META.get('HTTP_USER_AGENT', None),
                                str(FILENAME))
                return JsonResponse({'status': err, 'message': '删除失败'})
        else:
            event_log.delay(request.session.get('nickname', None), 1, 25,
                            '[{}] 文件不存在'.format(request.session.get('nickname', None)),
                            request.META.get('REMOTE_ADDR', None), request.META.get('HTTP_USER_AGENT', None),
                            str(FILENAME))
            return JsonResponse({'status': 25, 'message': '文件不存在'})



# ['DEFAULT_CHUNK_SIZE', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__',
# '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__
# ', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__',
# '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_get_name', '_name',
# '_set_name', 'charset', 'chunks', 'close', 'closed', 'content_type', 'content_type_extra', 'encoding', 'field_name',
# 'file', 'fileno', 'flush', 'isatty', 'multiple_chunks', 'name', 'newlines', 'open', 'read', 'readable', 'readinto',
# 'readline', 'readlines', 'seek', 'seekable', 'size', 'tell', 'truncate', 'writable', 'write', 'writelines']

templates/file/file_upload.html
{% extends "bash.html" %}

{% block title %}
    文件上传
{% endblock %}

{% load static %}
{% block css_style %}
    <link href="{% static 'inspinia/css/plugins/dropzone/basic.css' %}" rel="stylesheet">
    <link href="{% static 'inspinia/css/plugins/codemirror/codemirror.css' %}" rel="stylesheet">
    <link href="{% static 'inspinia/css/plugins/jasny/jasny-bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'inspinia/css/plugins/dropzone/dropzone.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
        <!-- Jasny -->
        <script src="{% static 'inspinia/js/plugins/jasny/jasny-bootstrap.min.js' %}"></script>

        <!-- DROPZONE -->
        <script src="{% static 'inspinia/js/plugins/dropzone/dropzone.js' %}"></script>

        <!-- CodeMirror -->
        <script src="{% static 'inspinia/js/plugins/codemirror/codemirror.js' %}"></script>
        <script src="{% static 'inspinia/js/plugins/codemirror/mode/xml/xml.js' %}"></script>
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>资料页</h2>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'users:index' %}">主页</a>
                        </li>
                        <li class="breadcrumb-item active">
                            <strong>文件上传</strong>
                        </li>
                    </ol>
                </div>
            </div>
        <div class="wrapper wrapper-content">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox">
                        <div class="ibox-title">
{#                            <h5>Dropzone.js</h5>#}
                            <h5>文件上传入口</h5>
                        </div>
                        <div class="ibox-content">

                            <p>
                                可以选择 <strong>5M </strong>以下的文件上传至服务器，每位用户的用户空间均为5GB，目前仅允许上传图片、文本，所有虚拟机共享该文件，位于 <strong>/opt </strong>文件夹下
                            </p>

                            <form class="dropzone" id="dropzoneForm">
                                {% csrf_token %}
                                <div class="fallback">
                                    <input name="file" type="file" multiple />
                                </div>
                            </form>
                            <br>
                            <p class="m-t-xs">
                                当<strong>所有容器到期时</strong>，空间内文件会被自动删除，<strong>请不要上传重要文件留存</strong>
                            </p>

                        </div>
                    </div>
                </div>
            </div>
            <script>
                /*Dropzone.options.dropzoneForm = {  // 使用下面的方法时此方法自动失效（from未设定或div class="dropzone"时）
                    paramName: "file", // The name that will be used to transfer the file
                    maxFilesize: 5, // MB
                    dictDefaultMessage: "<strong>在这里删除文件或点击上传。</strong></br>请勿恶意上传文件，当发现恶意行为时您的账户可能被禁用"
                };*/
                var myDropzone = new Dropzone("#dropzoneForm", {
                    url: "{{ request.path }}",//文件提交地址
                    method:"post",  //也可用put
                    paramName:"file", //默认为file
                    maxFiles:5,//一次性上传的文件数量上限
                    maxFilesize: 5, //文件大小，单位：MB
                    acceptedFiles: ".jpg,.gif,.png,.jpeg,.txt,.yaml,.dockerfile,.py,.java,.html,.js,.css,.jsp,.xml,.sql", //上传的类型
                    addRemoveLinks:true,
                    parallelUploads: 5,//一次上传的文件数量
                    //previewsContainer:"#preview",//上传图片的预览窗口
                    dictDefaultMessage:'拖动文件至此或者点击上传',
                    dictMaxFilesExceeded: "您最多一次只能上传5个文件！",
                    dictResponseError: '文件上传失败!',
                    dictInvalidFileType: "文件类型只能是*.jpg,*.gif,*.png,*.jpeg等。",
                    dictFallbackMessage:"浏览器不受支持",
                    dictFileTooBig:"文件过大上传文件最大支持.",
                    dictRemoveLinks: "删除",
                    dictCancelUpload: "取消",
                    //对一些方法的后续处理
                    init:function(){
                        this.on("addedfile", function(file) {
                            //上传文件时触发的事件
                            document.querySelector('div .dz-default').style.display = 'none';
                        });
                        this.on("success",function(file,data){
                            //上传成功触发的事件
                            console.log('上传成功');
                        });
                        this.on("error",function (file,data) {
                            //上传失败触发的事件
                            console.log('fail');
                            var message = '';
                            //lavarel框架有一个表单验证，
                            //对于ajax请求，JSON 响应会发送一个 422 HTTP 状态码，
                            //对应file.accepted的值是false，在这里捕捉表单验证的错误提示
                            if (file.accepted){
                                $.each(data,function (key,val) {
                                    message = message + val[0] + ';';
                                })
                                //控制器层面的错误提示，file.accepted = true的时候；
                                alert(message);
                            }
                        });
                        this.on("removedfile",function(file){
                            //删除文件时触发的方法(向后台发送删除文件请求)
                           $.post('{% url 'users:index' %}'+ file_id,{'_method':'DELETE'},function (data) {
                                console.log('删除结果:'+data.message);
                            })

                            document.querySelector('div .dz-default').style.display = 'block';
                        });
                    }
                });

                $(document).ready(function(){

                    var editor_one = CodeMirror.fromTextArea(document.getElementById("code1"), {
                        lineNumbers: true,
                        matchBrackets: true
                    });

                    var editor_two = CodeMirror.fromTextArea(document.getElementById("code2"), {
                        lineNumbers: true,
                        matchBrackets: true
                    });

                    var editor_two = CodeMirror.fromTextArea(document.getElementById("code3"), {
                        lineNumbers: true,
                        matchBrackets: true
                    });

                    var editor_two = CodeMirror.fromTextArea(document.getElementById("code4"), {
                        lineNumbers: true,
                        matchBrackets: true
                    });


                    $('.custom-file-input').on('change', function() {
                        let fileName = $(this).val().split('\\').pop();
                        $(this).next('.custom-file-label').addClass("selected").html(fileName);
                    });

               });
            </script>
        </div>
{% endblock %}