Vbox/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from users import urls as users_url
from selectos import urls as selectos_url
from webssh import urls as ssh_url
from file import urls as file_url
from component import urls as comp_url

from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(users_url)),
    path('selectos/', include(selectos_url)),
    path('file/', include(file_url)),
    path('webssh/', include(ssh_url)),
    path('webguacamole/', include('webguacamole.urls', namespace='webguacamole')),
    path('component/', include(comp_url)),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # url(r'^api-auth/', include('rest_framework.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

selectos/urls.py
from django.urls import path
from .views import Selectos, delete_user_deployment, pod_num, remove_all

urlpatterns = [
    path('select/', Selectos.as_view(), name='select'),
    path('delete_user_deployment/', delete_user_deployment, name='delete_user_deployment'),
    path('get_pod_num/', pod_num, name='get_pod_num'),
    path('remove_all/', remove_all, name='remove_all_pod'),
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from .views import Login, logout, Registered, profile, index, bash_info

app_name = 'users'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout', logout, name='logout'),
    path('registered/', Registered.as_view(), name='registered'),
    path('profile/', profile, name='profile'),
    path('index/', index, name='index'),
    path('bash_info/', bash_info, name='bash_info'),  # 异步加载信息传递方案
]

selectos/models.py
from django.db import models
import time
from users.models import UserProfile

# Create your models here.


class Systemos(models.Model):
    """
    any user，one namespace，one service，limit three deployment（pod）
    username = namespace-name = service-name = pod-label
    deployment-name = create-time md5
    port in pod
    node_port is 80
    """

    os_list = (
        (0, 'Ubuntu'),  # 默认ubuntu18.04
        (1, 'Centos'),
        (2, 'Ubuntu 16.04'),
        (3, 'Ubuntu 14.04'),
    )

    language_list = (
        (0, 'Python2'),
        (1, 'Python3'),
        (2, 'java1.8'),
    )

    database_list = (
        (0, 'null'),
        (1, 'mysql5.7'),
        (2, 'Redis'),
        (3, 'MongoDB'),
    )

    active = (
        (0, '正在生成'),
        (1, '正常运行'),
        (2, '异常状态'),
        (3, '正在删除')
    )

    user = models.ForeignKey('users.UserProfile', to_field='username', related_name='dep_user', null=False, on_delete=models.CASCADE)
    namespace = models.CharField(max_length=63, null=False, default='default', verbose_name='命名空间')
    deployment = models.CharField(unique=True, max_length=64, default='emp_name', null=False,
                                  verbose_name='deployment_name')
    version = models.CharField(max_length=8, null=False, default='apps/v1', verbose_name='容器版本')
    labels = models.CharField(max_length=63, null=False, default='username', verbose_name='容器标签')
    create_time = models.CharField(max_length=63, null=False, default='0', verbose_name='创建时间戳')
    storage = models.IntegerField(null=False, default='5', verbose_name='硬盘容量G')
    active_status = models.SmallIntegerField(null=False, default=1, verbose_name='容器状态')

    os = models.CharField(max_length=64, choices=os_list, null=False, verbose_name='操作系统')
    cpus = models.IntegerField(null=False, default=1, verbose_name='cpu个数')
    ram = models.IntegerField(null=False, default=2048, verbose_name='内存容量')
    language = models.CharField(max_length=64, choices=language_list, null=True, blank=True, verbose_name='编程语言')
    database = models.CharField(max_length=64, choices=database_list, null=True, blank=True, verbose_name='数据库')
    is_vnc = models.BooleanField(null=False, default=True, verbose_name='是否需要vnc')  # 默认需要的
    port = models.IntegerField(null=True, blank=True, verbose_name='pod开放端口')  # 只允许有一个
    nodeport = models.IntegerField(null=True, blank=True, default=0, verbose_name='service外部端口')
    use_time = models.IntegerField(null=False, verbose_name='租用时长')  # 最长24小时

    class Meta:
        verbose_name = '用户配置'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.deployment)


class ExceptDep(models.Model):
    namespace = models.CharField(max_length=63, null=False, default='default', verbose_name='命名空间')
    deployment = models.CharField(unique=True, max_length=64, default='emp_name', null=False,
                                  verbose_name='deployment_name')
    cpus = models.IntegerField(null=False, default=1, verbose_name='cpu个数')  # 创建时数据校验，异常容器也占用资源
    ram = models.IntegerField(null=False, default=2048, verbose_name='内存容量')
    create_time = models.DateTimeField('上传时间', auto_now_add=True)

    class Meta:
        verbose_name = '异常表'  # deployment数据存入失败时
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.deployment)

# class TerminalLog(models.Model):
#     user = models.CharField(max_length=64, verbose_name='用户')
#     depname = models.CharField(max_length=64, verbose_name='DEPLOYMENT')
#     ip = models.GenericIPAddressField(verbose_name='PODIP')
#     protocol = models.CharField(max_length=64, default='ssh', verbose_name="协议")
#     port = models.SmallIntegerField(default=22, verbose_name='端口')
#     cmd = models.TextField('命令详情', blank=True, null=True)
#     detail = models.CharField(max_length=128, blank=True, null=True, verbose_name="结果详情(文件名)")
#     address = models.GenericIPAddressField('IP地址', blank=True, null=True, verbose_name="客户端ip")
#     useragent = models.CharField(max_length=512, blank=True, null=True, verbose_name='User_Agent')
#     start_time = models.DateTimeField('会话开始时间')
#     create_time = models.DateTimeField('事件时间', auto_now_add=True)
#
#     def __str__(self):
#         return self.user
#
#     class Meta:
#         ordering = ["-create_time"]
#         verbose_name = '在线会话日志'
#         verbose_name_plural = '在线会话日志'
#
#
# class TerminalSession(models.Model):
#     PROTOCOL_CHOICES = (
#         (1, 'ssh'),
#         (2, 'vnc'),
#     )
#
#     TYPE_CHOICES = (
#         (1, 'webssh'),
#         (2, 'webvnc'),
#     )
#
#     name = models.CharField(max_length=512, verbose_name='会话名称')
#     group = models.CharField(default='chat_default', max_length=512, verbose_name='会话组')
#     type = models.SmallIntegerField(default=1, choices=TYPE_CHOICES, verbose_name='类型')
#     user = models.CharField(max_length=128, verbose_name='用户')
#     host = models.GenericIPAddressField(verbose_name='主机')
#     port = models.SmallIntegerField(default=22, verbose_name='端口')
#     username = models.CharField(max_length=128, verbose_name='账号')
#     protocol = models.SmallIntegerField(default=1, choices=PROTOCOL_CHOICES, verbose_name='协议')
#     address = models.GenericIPAddressField('IP地址', blank=True, null=True)
#     useragent = models.CharField(max_length=512, blank=True, null=True, verbose_name='User_Agent')
#     locked = models.BooleanField(default=False, verbose_name='会话状态')
#     create_time = models.DateTimeField('会话时间', auto_now_add=True)
#
#     def __str__(self):
#         return '{0}'.format(self.name)
#
#     class Meta:
#         ordering = ["-create_time"]
#         verbose_name = '在线会话'
#         verbose_name_plural = '在线会话'

selectos/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, JsonResponse
import json
from django.views.generic import View

from django.views.decorators.cache import cache_page  # 缓存装饰器
# @cache_page(5)  # 部分数据需要实时更新，所以还是使用redis作为缓存服务器，cache方法实现缓存
from django.core.cache import cache  # 操作缓存 clear() 清空所有缓存
# from django.views.decorators.cache import cache_control
# @cache_control(private=True)  # 私有缓存标识
# @cache_control(must_revalidate=True, max_age=3600)  # 每次访问均验证缓存，最长保存3600s

# 对类视图使用装饰器需要使用这个方法
from django.utils.decorators import method_decorator

from users.models import UserProfile
from selectos.models import Systemos, ExceptDep


from tools.tool import get_deploy_name, not_cache
from tools.k8s import KubeApi

from Vbox import celery_app
from .tasks import *
from tools.tool import login_required


@celery_app.task
def delete_this_namespace(name):
    task = KubeApi(name)
    info = task.delete_user_namespace()
    print(info)


@method_decorator(login_required, name='dispatch')  # dispatch代表全部方法
# name实际上等于在这类中继承了View的dispatch方法
class Selectos(View):

    @method_decorator(cache_page(5))  # 对单个方法加装饰器
    def get(self, request):  # 后期添加访问限制
        data = {}
        data['array'] = range(1, 5)
        data['os_list'] = list(Systemos.os_list)
        data['language_list'] = list(Systemos.language_list)
        data['database_list'] = list(Systemos.database_list)
        img = UserProfile.objects.get(username=request.session.get('username', None)).avatar
        nickname = request.session.get('nickname', None)
        role = request.session.get('role', None)
        page = '容器信息'
        container_info = self.container_list(request)
        nickname = request.session.get('nickname', None)
        event_log.delay(nickname, 1, 20, '[{}] 访问容器信息页面'.format(nickname),
                        request.META.get('REMOTE_ADDR', None), request.META.get('HTTP_USER_AGENT', None),
                        str(request.headers))
        return render(request, 'selectos/inspiration.html', locals())

    def container_list(self, request):
        username = str(request.session.get('username', None))
        container_info = Systemos.objects.filter(user=username, active_status=1)
        return container_info

    def post(self, request):
        imgname_list = {
            'Ubuntu': 'dorowu/ubuntu-desktop-lxde-vnc',  # 18.04
            'Centos': 'centos:7',
            'Ubuntu 16.04': 'dorowu/ubuntu-desktop-lxde-vnc',
            'Ubuntu 14.04': 'dorowu/ubuntu-desktop-lxde-vnc',
        }
        cpu_limit = {  # CPU time
            '1': '500m',  # 1/2
            '2': '1000m',
            '3': '1500m',
            '4': '2000m',
        }
        os = request.POST.get('os')
        language = request.POST.get('language')
        database = request.POST.get('database')
        use_time = request.POST.get('use_time')
        cpus = str(request.POST.get('cpus'))

        namespace = request.session.get('username', None)
        VERSION = 'apps/v1'
        DEPNAME, create_time = get_deploy_name()
        if os in imgname_list.keys():
            IMGNAME = imgname_list[os]
        else:
            return JsonResponse({"status": 403, "error": "参数信息错误，请刷新界面后重试"}, safe=False)

        # readUint32: unexpected character: \\ufffd, error found in #10 byte of ...|erPort\\": \\"59999\\"}],
        # 单引号，必须正整形，未知bug
        port = request.POST.get('port')
        if not port:
            port = 64444
        PORTS = int(port)

        DIR = '/home/soul/tools/' + str(namespace)
        if cpus in cpu_limit.keys():
            CPUS = cpu_limit[cpus]  # 单位不同
        else:
            return JsonResponse({"status": 403, "error": "参数信息错误，请刷新界面后重试"}, safe=False)
        MEMORY = str(request.POST.get('memory')) + 'Mi'
        EPH = '5Gi'

        # 创建异步创建任务
        create_deployment(namespace, VERSION, DEPNAME, IMGNAME, PORTS, DIR, CPUS, MEMORY, EPH, use_time, request)
        # 异步保存数据
        save_deployment_info(
            request, user_id=namespace, deployment=DEPNAME, version=VERSION, labels=DEPNAME[:25],
            create_time=create_time, os=os, cpus=request.POST.get('cpus'),
            ram=request.POST.get('memory'), language=language, database=database, port=port,
            use_time=use_time, namespace=namespace
        )
        return JsonResponse({"status": 200, "error": "数据提交成功，正在生成"}, safe=False)


# @login_required
def delete_user_deployment(request):
    """
    删除主机
    :param request: deployment id
    :return: 删除结果
    """
    dep_id = request.GET.get('dep_id')
    namespace = request.session.get('username', None)
    try:  # 立即标注删除
        dep_name = Systemos.objects.get(id=dep_id).deployment
        active = Systemos.objects.get(
            Q(user_id=str(namespace)) & Q(deployment=str(dep_name))
        )
        active.active_status = 3
        active.save()
        delete_deployment(request, namespace, dep_name)
    except Exception as err:
        event_log.delay(request.session.get('nickname', None), 1, 11,
                        '[{}] 主机参数不存在'.format(request.session.get('nickname', None)),
                        request.META.get('REMOTE_ADDR', None), request.META.get('HTTP_USER_AGENT', None),
                        str(err))
    return JsonResponse({"status": 200, "error": "删除请求已提交"}, safe=False)


# @login_required
# @cache_page(5)  # 5秒缓存，与容器列表缓存时间相同
def pod_num(request):
    """
    虚拟主机数量
    :param request:
    :return: 主机数量
    """
    key_pod_num = str(request.session.get('username', None)) + '_pod_num'  # 缓存关键字，防重复
    num = cache.get(key_pod_num)  # 不存在就是None
    username = request.session.get('username', None)
    fun_name = request.GET.get("getpodsum")  # jsonp ajax提交时函数名
    if not num:
        not_cache(key_pod_num, username)
        data = {'sum': cache.get(key_pod_num)}  # 直接重新读取缓存
    else:
        # 缓存存在
        data = {'sum': num}
    return HttpResponse("%s('%s')" % (fun_name, json.dumps(data)))


@celery_app.task
def remove_all(request):
    namespace = request.session.get('username', 'default')
    kube = KubeApi(namespace)
    status, data = kube.delete_deployment("")
    print(status)
    Systemos.objects.filter(namespace__exact=namespace).delete()
    key_pod_num = namespace + '_pod_num'
    cache.set(key_pod_num, 0, None)  # 当前容器数量
    return JsonResponse({"status": 200, "error": data}, safe=False)

templates/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>运维管理系统登陆</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
        integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <style>
	/* 页面加载完后再显示，更好的显示特效 */
	body {
		display : none;
	}
  </style>

</head>
<body class="hold-transition login-page content-list">
<div class="login-box">
  <div class="login-logo">
      <b>Welcome to Vbox</b><br>
      <h6>为了每一个即时的灵感</h6>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
	  {% if error_message %}
	  <div class="alert alert-warning">{{ error_message }}</div>
	  {% endif %}

      <p class="login-box-msg">登陆</p>

      <form action="{% url 'users:login' %}" method="post" class="mb-2 login-form" onsubmit="return login_form();">
		{% csrf_token %}
        <div class="input-group">
          <input type="username" class="form-control" name="username" placeholder="用户名" id="username" value="systemime" onkeyup="check_username();" onblur="check_username();">
          <div class="input-group-append input-group-text" id="username-icon">
              <span class="fas fa-envelope"></span>
          </div>
        </div>
		<div class="input-group mb-3">
			<span id="username_error" style="color:red;"></span>
		</div>

        <div class="input-group">
          <input type="password" class="form-control" name="password" placeholder="密码" id="password" value="123456" onkeyup="check_password();" onblur="check_password();">
          <div class="input-group-append input-group-text" id="password-icon">
              <span class="fas fa-lock"></span>
          </div>
        </div>
		<div class="input-group mb-3">
			<span id="password_error" style="color:red;"></span>
		</div>
        <div class="row">
          <!-- /.col -->
          <div class="col">
            <button type="submit" class="btn btn-success btn-block">确定</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mb-1">
        <a href="#">忘记密码？</a>
      </p>
      <p class="mb-1">
        <a href="{% url 'users:registered' %}">注册用户</a>
      </p>
      <!--p class="mb-0">
        <a href="register.html" class="text-center">注册账号</a>
      </p-->
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script>
	// 校验表单数据
	check_username = function() {
		var username = $('#username').val();
		if (username == '') {
			$('#username').removeClass("border-success");
			$('#username').addClass("border-danger");
			$('#username-icon').removeClass("border-success");
			$('#username-icon').addClass("border-danger");
			$('#username_error').text('用户名不能未空');
			return false;
		} else if(/[@#\$%\^&\*]+/g.test(username)) {	// 正则判断
			$('#username').removeClass("border-success");
			$('#username').addClass("border-danger");
			$('#username-icon').removeClass("border-success");
			$('#username-icon').addClass("border-danger");
			$('#username_error').text('用户名不能存在特殊符号');
			return false;
		} else {
			$('#username').removeClass("border-danger");
			$('#username').addClass("border-success");
			$('#username-icon').removeClass("border-danger");
			$('#username-icon').addClass("border-success");
			$('#username_error').text('');
			return true;
		};
	}

	check_password = function() {
		var password = $('#password').val();
		if (password == '') {
			$('#password').removeClass("border-success");
			$('#password').addClass("border-danger");
			$('#password-icon').removeClass("border-success");
			$('#password-icon').addClass("border-danger");
			$('#password_error').text('密码不能为空');
			return false;
		} else if(password.length < 6) {
			$('#password').removeClass("border-success");
			$('#password').addClass("border-danger");
			$('#password-icon').removeClass("border-success");
			$('#password-icon').addClass("border-danger");
			$('#password_error').text('密码长度必须大于等于6个字符');
			return false;
		} else {
			$('#password').removeClass("border-danger");
			$('#password').addClass("border-success");
			$('#password-icon').removeClass("border-danger");
			$('#password-icon').addClass("border-success");
			$('#password_error').text('');
			return true;
		};
	}
	// 校验表单数据

	login_form = function() {
		var check_right = new Array();
		var username = $('#username').val();
		check_right[0] = check_username();

		var password = $('#password').val();
		check_right[1] = check_password();
		// console.log(check_right)
		if (!/false/.test(check_right)) {
			return true;
		} else {
			return false;
		};
	};
</script>

<!-- 动画特效 -->
<script src="//cdn.bootcss.com/velocity/1.5.2/velocity.min.js"></script>
<script src="//cdn.bootcss.com/velocity/1.5.2/velocity.ui.min.js"></script>
<script>
	$(".content-list").velocity("transition.slideDownIn", { stagger: 150, drag: true });
	//$(".content-list").velocity("transition.slideRightBigIn", { stagger: 120, drag: true });
</script>

<!-- 页面加载完后再显示，更好的显示特效 -->
<script>
	document.addEventListener("DOMContentLoaded", function(){
		$("body").css("display", "block");
	});
</script>

</body>
</html>

templates/registered.html
<!DOCTYPE html>
<html>
{% load static %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Vbox 1.0.0 | 注册</title>

    <link href="{% static 'inspinia/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'inspinia/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'inspinia/css/plugins/iCheck/custom.css' %}" rel="stylesheet">
    <link href="{% static 'inspinia/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'inspinia/css/style.css' %}" rel="stylesheet">
    <!-- Sweet Alert -->
    <link href="{% static 'inspinia/css/plugins/sweetalert/sweetalert.css' %}" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>
                <h1 class="logo-name">Vbox</h1>
            </div>
            <h3>注册平台账户</h3>
            <p>创建账户以查看更多好玩功能</p>
            <form class="m-t" role="form" action="" onSubmit="return confirm();">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" id="new_username" name="new_username" class="form-control" placeholder="用户名" required="">
                </div>
                <div class="form-group">
                    <input type="text" id="new_nickname" name="new_nickname" class="form-control" placeholder="昵称" required="">
                </div>
                <div class="form-group">
                    <input type="email" id="new_email" name="email" class="form-control" placeholder="电子邮件" required="">
                </div>
                <div class="form-group">
                    <input type="password" id="new_passwd" name="password" class="form-control" placeholder="密码" required="">
                </div>
                <div class="form-group">
                    <div class="checkbox i-checks"><label> <input type="checkbox"><i></i> 同意条款和政策 </label></div>
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b demo2">注册</button>

                <p class="text-muted text-center"><small>已经有一个帐户?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="{% url 'users:login' %}">登录</a>
            </form>
            <p class="m-t"> <small>Copyright</strong> inspinia 2.9.2 &copy; 2017-2018</small> </p>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="{% static 'inspinia/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'inspinia/js/popper.min.js' %}"></script>
    <script src="{% static 'inspinia/js/bootstrap.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static 'inspinia/js/plugins/iCheck/icheck.min.js' %}"></script>
    <!-- Custom and plugin javascript -->
    <script src="{% static 'inspinia/js/inspinia.js' %}"></script>
    <script src="{% static 'inspinia/js/plugins/pace/pace.min.js' %}"></script>
    <!-- Sweet alert -->
    <script src="{% static 'inspinia/js/plugins/sweetalert/sweetalert.min.js' %}"></script>
    <script>
        $(document).ready(function(){
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });

            var y_name = /^[a-zA-Z'][a-zA-Z'][a-zA-Z'][a-zA-Z-' ]+[a-zA-Z']?$/;
            $("#new_username").change(function(){
                if(!y_name.test($('#new_username').val())){
                    swal({
                        title: "用户名填写错误",
                        text: "字母或与数字的组合，最短需要四个字符哟"
                    });
                    $(this).val("");
                }    
            });
            var y_nick = /^[\u4E00-\u9FA5A-Za-z\s]+(·[\u4E00-\u9FA5A-Za-z]+)*$/;
            $("#new_nickname").change(function(){
                if(!y_nick.test($('#new_nickname').val())){
                    swal({
                        title: "昵称填写错误",
                        text: "唔，请三思，不如换个昵称试试？"
                    });
                    $(this).val("");
                }    
            });
            var y_eamil = /^[a-z\d]+(\.[a-z\d]+)*@([\da-z](-[\da-z])?)+(\.{1,2}[a-z]+)+$/;
            $("#new_email").change(function(){
                if(!y_eamil.test($('#new_email').val())){
                    swal({
                        title: "邮箱填写错误",
                        text: "您的邮箱看起来有些特别，要不检查一下拼写？"
                    });
                    $(this).val("");
                }    
            });

            var y_passwd = /.{6}/;
            $("#new_passwd").change(function(){
                if(!y_passwd.test($('#new_passwd').val())){
                    swal({
                        title: "密码长度太短啦",
                        text: "做人要6，密码长度怎么能短？"
                    });
                    $(this).val("");
                }    
            });


            $('.demo2').click(function(){
                var name = $('#new_username').val();
                var nick = $('#new_nickname').val();
                var email = $('#new_email').val();
                var passwd = $('#new_passwd').val();

                if (name && nick && email && passwd) {
                    $.ajax({
                        url:"{% url 'users:registered' %}",
                        type:"post",
                        data: {'username': name, 'nickname': nick, 'email': email, 'passwd': passwd, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                        async: true,  // 防止狗屁浏览器拦截
				        timeout: 5000,
				        cache: true,
                        //var obj = eval("("+data+")");
                        beforeSend: LoadFunction, //加载执行方法
				        error: errFunction,  //错误执行方法
				        success: succFunction, //成功执行方法
                    });
                    $('#new_username').focus();
                    return false;
                }
                else {
                    swal({
                        title: "请检查填写信息",
                        text: "感谢您对本系统的信任，但您似乎有信息没有填写？"
                    });　　
                    $('#new_username').focus();
                    return false;
                }

                function LoadFunction() {
                    //$("#aboutcontent").html('删除中...');
                    //alert('删除中');
                };

                function errFunction() {
                    swal({
                        title: "注册失败！",
                        text: "系统发生未知错误，请重新注册",
                    });
                };

                function succFunction(res) {
                    swal({
                        title: res.title,
                        text: res.error,
                        type: "success"
                    });
                    setTimeout(function(){
                        window.location.href="{% url 'users:login' %}";
                    },1500);
                };
            });
        });

    </script>
</body>

</html>

templates/talk.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% load staticfiles %}
    <div id="contents" style="height:500px;overflow:auto;"></div>
    <div>
        <textarea id="msg"></textarea>
        <a href="javascript:;" onclick="sendMsg()">发送</a>
    </div>
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript">
        var ws = new WebSocket("ws://192.168.221.139:60015/chat?token={{ encoded }}");
        ws.onmessage = function(e) {
            $("#contents").append("<p>" + e.data + "</p>");
        }
        function sendMsg() {
            var msg = $("#msg").val();
            ws.send(msg);
            $("#msg").val("");
        }
    </script>
</body>
</html>